version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies-update"
    ignore:
      - dependency-name: "apscheduler"
    commit-message:
      prefix: "[PIP]"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies-update"
    commit-message:
      prefix: "[DOCKER]"
