language: python

dist: focal

python:
  - '3.9'

install:
  - pip install '.[dev]'

script:
  - dikort $TRAVIS_COMMIT_RANGE
  - black --check cve_bot
  - isort -c cve_bot
  - flake8 cve_bot
  - pytest --cov

after_success:
  - codecov

notifications:
  slack:
    secure: DrJwnRIjELEI5LUw48fBcgdm26c38GHxwrOr3UOLzBGJmLT2PhlyXo4zBYyTtuHZHPL6O+nSjhigmPxcMv0OboY5GxZV0PS614b5l4U8viwHIoDbQ99NWB8FjCUoLucKWDTM3kaILX5Vhp2FK/Jenp+lW9LeWZc6tCly+b0N30kOxKEjFRRd2hyl6QgmsPA6qW1cQPdhiwTfzhTLa1+ON4c/XxuXLQKuCMRSF5L8nlTIVf6Cd/DZs8oagL8e/vhHgv0GMyNAMMpz0N448XMYpPeKMSG6SgjXQVfu0tuU/xPoX0Bt9TdYyPuWnl4UMw0MPfhE/7cJwCW3BXK9eGIYU60Q7r8QbP7Ia6StVT2ZAe5wWaxYzEMQCiaNiCGncdiWuVeyce3Zh3KXtsx2h3zNs/FD405D5oT/E7ZDdICQFT1Lpx9BBsCjWKiX464r/ukcZirIoS94dAuOcksmPeuyUmd9DuQLbB2RHkh82VCcWToAr6wS6k3NlSbK46tYngXsMi9isa5RdjGE79yvhaFr6A7cA895gR1XT5ifSlfIwTk3NYsFZ1w6qPUcoCotF0EJGI2Zr5Fk5y0k0/Q/9hVz7bmixrGTQq4cQkNx7nteKs+B44nChqoADCGkXx0bSgwF+rjkkPQAU9tto9XRxlYqH9J9MXBcwmdphZxIgdCKYhw=
    on_success: change
    on_failure: always
