---
- name: Deploy to production
  hosts: prod
  become: true

  tasks:
    - name: Copy data directory
      ansible.builtin.file:
        path: /srv/data
        state: directory
        mode: '0600'

    - name: Copy env file
      ansible.builtin.copy:
        src: production.env
        dest: /srv/production.env
        decrypt: yes
        owner: root
        group: root
        mode: '0600'

    - name: Install ansible docker deps
      pip:
        name: docker-py==1.10.6

    - name: Create a container
      docker_container:
        name: cve-bot
        image: weastur/cve_bot:latest
        volumes:
          - /srv/data:/cve_bot
        hostname: cve-bot
        restart_policy: always
        env_file: /srv/production.env
